name: 'HookFlo Notify Action'
description: 'Simple, production ready GitHub Action to send JSON alerts via POST to Slack, email, logging, and more.'
author: 'HookFlo'

inputs:
  webhook_url:
    description: 'Target endpoint URL where notifications should be delivered.'
    required: true

  webhook_id:
    description: 'Header value to be sent as x-webhook-id.'
    required: true

  webhook_secret:
    description: 'Header value to be sent as x-webhook-secret.'
    required: true

  payload:
    description: 'Optional JSON string to send as the request body.'
    required: false
    default: '{}'

runs:
  using: 'composite'
  steps:
    - name: Send Notification via Curl
      shell: bash
      run: |
        echo "Sending notification to ${{ inputs.webhook_url }}"
        curl -s -X POST "${{ inputs.webhook_url }}" \
             -H "Content-Type: application/json" \
             -H "x-webhook-id: ${{ inputs.webhook_id }}" \
             -H "x-webhook-secret: ${{ inputs.webhook_secret }}" \
             -d '${{ inputs.payload }}'

branding:
  icon: 'bell'
  color: 'purple'
